### ISSUE TITLE
不行，无法复现

### ISSUE THREAD

**Issue by ljjsimon** [ShineChen1024/oms-Diffusion#14]
下面是我生成的，衣服上的字和原图差很多
![out_0](https://github.com/ShineChen1024/oms-Diffusion/assets/1535231/84e313bd-db5c-46f2-9aea-218b6e64cb6f)
![out_1](https://github.com/ShineChen1024/oms-Diffusion/assets/1535231/198a77c9-52d7-43b5-b9f6-0bbef6575d2a)
![out_2](https://github.com/ShineChen1024/oms-Diffusion/assets/1535231/8d5124b7-974e-4d38-8663-edb2ec7a2428)
![out_3](https://github.com/ShineChen1024/oms-Diffusion/assets/1535231/aec1a614-bb95-4fc1-94e4-53cf86085f89)

**Comment by dizhenx** [comment]
原图发出来看看

**Comment by ShineChen1024** [comment]
enlarge the width or height will show you more details, 512*384 is the Minimum resolution.
