### ISSUE TITLE
用gradio_controlnet_openpose.py试跑无法获取demo同样效果？

### ISSUE THREAD

**Issue by jeffreyrobeson** [ShineChen1024/oms-Diffusion#17]
![6e0d4a0b5f6068bf953c1252390fce30](https://github.com/ShineChen1024/oms-Diffusion/assets/132809848/aada9c2c-f1ac-4c97-b094-408e2e318fbb)

**Comment by jeffreyrobeson** [comment]
![133cf51c3da595f8d80ef10d2ae0ea69](https://github.com/ShineChen1024/oms-Diffusion/assets/132809848/a4572cd9-117a-4fcd-b802-a54919d6767c)

**Comment by ShineChen1024** [comment]
![image](https://github.com/ShineChen1024/oms-Diffusion/assets/16463912/26217155-291d-4a47-a557-54170dc02d7d)
I dont know what happend, but in the second image the cloth_mask seem to be total black.

**Comment by ClothingAI** [comment]
Can someone provide a json file for this please?
