### ISSUE TITLE
Is the inpainting pipeline the same as OOTDiffusion?

### ISSUE THREAD

**Issue by feiyangsuo** [ShineChen1024/oms-Diffusion#18]
Thanks for the great work of yours!

Noticed that you got another work OOTDiffusion which has similar results as the inpainting demo of this work. Is OOTDiffusion using the same method as this one? Or perhaps using shared model structure/weights?

**Comment by ShineChen1024** [comment]
their inpainting mode are different. the inpainting ability of oms depend on external controlnet network, ootd is specially designed for inpainting task.
