### ISSUE TITLE
安装模块有问题

### ISSUE THREAD

**Issue by Crazy-CYZ** [ShineChen1024/oms-Diffusion#24]
`pip install torch==2.0.1 torchvision==0.15.2 numpy==1.25.1 diffusers==0.25.1 opencv-python==4.8.0 transformers==4.31.0 gradio==4.16.0 safetensors==0.3.1 controlnet-aux==0.0.6 accelerate-0.21.0`

以上模块部分的opencv-python==4.8.0显示没这个版本，accelerate-0.21.0这个有问题，应该是accelerate==0.21.0

我修改后成功运行
`pip install torch==2.0.1 torchvision==0.15.2 numpy==1.25.1 diffusers==0.25.1 opencv-python==4.8.0.76 transformers==4.31.0 gradio==4.16.0 safetensors==0.3.1 controlnet-aux==0.0.6 accelerate==0.21.0`

**Comment by ShineChen1024** [comment]
Ths
