### ISSUE TITLE
where should I put the checkpoint

### ISSUE THREAD

**Issue by XiangjiBU** [ShineChen1024/oms-Diffusion#29]
thanks for great job!
I download the checkpoints from huggingface, but still don't know where should I put it, could you tell me?
Just put 'oms_diffusion_768.safetensors' in 'checkpoints' folder?

**Comment by XiangjiBU** [comment]
solved!

**Comment by ShineChen1024** [comment]
anywhere, and let the program know where it saved by specify-[-model_path], see the guidance in inference.
